# -*- coding: utf-8 -*-
"""Netflix_Stocks

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOdAETf1o75CAN3qLSvFswU1hjZXjXIu
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

df = pd.read_csv('/content/Netflix.csv')

df.head()

df.info()

df['Date']= pd.to_datetime(df['Date'])
df['Year'] = pd.DatetimeIndex(df['Date']).year

df.info()

df.head()

df.set_index('Date', inplace=True)

df.head()

"""Number of volume shares trade by 2022"""

sns.lineplot(x=df.index,y=df['Volume'],label='Volume of shares')

"""Opening share price of netflix stock"""

sns.lineplot(x=df.index,y=df['Open'],label='Opening Share price')

"""Closing price of netflix stocts"""

sns.lineplot(x=df.index,y=df['Close'],label='Closing  Share price')

sns.lineplot(x=df.index,y=df['High'],label='High price of share')

"""HIgh and low price show by day and months"""

fig,(ax1,ax2) = plt.subplots(2,figsize=(10,8))
df.groupby(df.index.day).mean().plot(y='High',ax=ax1)
df.groupby(df.index.month).mean().plot(y='Low',ax=ax2)

df1 = df.groupby('Year')["Volume"].sum()
df1

"""# New Section"""

fig = px.bar(df1, y ='Volume', title = 'Number of shares traded per year', color = 'Volume')
fig.show()

"""Top five Low and High shares all the time"""

Low_five= df.sort_values(by='Low',ascending=True).head(5)
Low_five['Low']

Top_five=df.sort_values(by='High',ascending=False).head(5)
Top_five['High']

fig,axes =plt.subplots(nrows=1,ncols=2,sharex=True,figsize=(12,5))

sns.lineplot(ax = axes[0],y=df['High'],x=df.index,color='green')
sns.lineplot(ax = axes[1],y=df['Low'],x=df.index,color='red')

